package com.keven.kubi.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.keven.kubi.bean.DailyProductBean;
import com.keven.kubi.bean.FoodHourBean;
import com.keven.kubi.bean.FoodProductionBean;
import com.keven.kubi.bean.HourlyAlarmBean;

import com.keven.kubi.db.greendao.DailyProductBeanDao;
import com.keven.kubi.db.greendao.FoodHourBeanDao;
import com.keven.kubi.db.greendao.FoodProductionBeanDao;
import com.keven.kubi.db.greendao.HourlyAlarmBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dailyProductBeanDaoConfig;
    private final DaoConfig foodHourBeanDaoConfig;
    private final DaoConfig foodProductionBeanDaoConfig;
    private final DaoConfig hourlyAlarmBeanDaoConfig;

    private final DailyProductBeanDao dailyProductBeanDao;
    private final FoodHourBeanDao foodHourBeanDao;
    private final FoodProductionBeanDao foodProductionBeanDao;
    private final HourlyAlarmBeanDao hourlyAlarmBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dailyProductBeanDaoConfig = daoConfigMap.get(DailyProductBeanDao.class).clone();
        dailyProductBeanDaoConfig.initIdentityScope(type);

        foodHourBeanDaoConfig = daoConfigMap.get(FoodHourBeanDao.class).clone();
        foodHourBeanDaoConfig.initIdentityScope(type);

        foodProductionBeanDaoConfig = daoConfigMap.get(FoodProductionBeanDao.class).clone();
        foodProductionBeanDaoConfig.initIdentityScope(type);

        hourlyAlarmBeanDaoConfig = daoConfigMap.get(HourlyAlarmBeanDao.class).clone();
        hourlyAlarmBeanDaoConfig.initIdentityScope(type);

        dailyProductBeanDao = new DailyProductBeanDao(dailyProductBeanDaoConfig, this);
        foodHourBeanDao = new FoodHourBeanDao(foodHourBeanDaoConfig, this);
        foodProductionBeanDao = new FoodProductionBeanDao(foodProductionBeanDaoConfig, this);
        hourlyAlarmBeanDao = new HourlyAlarmBeanDao(hourlyAlarmBeanDaoConfig, this);

        registerDao(DailyProductBean.class, dailyProductBeanDao);
        registerDao(FoodHourBean.class, foodHourBeanDao);
        registerDao(FoodProductionBean.class, foodProductionBeanDao);
        registerDao(HourlyAlarmBean.class, hourlyAlarmBeanDao);
    }
    
    public void clear() {
        dailyProductBeanDaoConfig.getIdentityScope().clear();
        foodHourBeanDaoConfig.getIdentityScope().clear();
        foodProductionBeanDaoConfig.getIdentityScope().clear();
        hourlyAlarmBeanDaoConfig.getIdentityScope().clear();
    }

    public DailyProductBeanDao getDailyProductBeanDao() {
        return dailyProductBeanDao;
    }

    public FoodHourBeanDao getFoodHourBeanDao() {
        return foodHourBeanDao;
    }

    public FoodProductionBeanDao getFoodProductionBeanDao() {
        return foodProductionBeanDao;
    }

    public HourlyAlarmBeanDao getHourlyAlarmBeanDao() {
        return hourlyAlarmBeanDao;
    }

}
