package com.keven.kubi.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.keven.kubi.bean.HourlyAlarmBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOURLY_ALARM_BEAN".
*/
public class HourlyAlarmBeanDao extends AbstractDao<HourlyAlarmBean, Long> {

    public static final String TABLENAME = "HOURLY_ALARM_BEAN";

    /**
     * Properties of entity HourlyAlarmBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property HourTimeStamp = new Property(1, long.class, "hourTimeStamp", false, "HOUR_TIME_STAMP");
        public final static Property IsRinged = new Property(2, boolean.class, "isRinged", false, "IS_RINGED");
    };


    public HourlyAlarmBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HourlyAlarmBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOURLY_ALARM_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"HOUR_TIME_STAMP\" INTEGER NOT NULL UNIQUE ," + // 1: hourTimeStamp
                "\"IS_RINGED\" INTEGER NOT NULL );"); // 2: isRinged
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOURLY_ALARM_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HourlyAlarmBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getHourTimeStamp());
        stmt.bindLong(3, entity.getIsRinged() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HourlyAlarmBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getHourTimeStamp());
        stmt.bindLong(3, entity.getIsRinged() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HourlyAlarmBean readEntity(Cursor cursor, int offset) {
        HourlyAlarmBean entity = new HourlyAlarmBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // hourTimeStamp
            cursor.getShort(offset + 2) != 0 // isRinged
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HourlyAlarmBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHourTimeStamp(cursor.getLong(offset + 1));
        entity.setIsRinged(cursor.getShort(offset + 2) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HourlyAlarmBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HourlyAlarmBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
